Repository wisemen-digital/AndroidCore, pull requests merged in 2021-04, with the labels that each got.

#28 Feature/#35 update libraries and more
  build.gradle
  src/main/java/be/appwise/core/extensions/libraries/EasyImageExtensions.kt
  src/main/java/be/appwise/core/networking/NetworkingUtil.kt
  src/main/java/be/appwise/core/networking/bagel/BagelMessage.kt
  src/main/java/be/appwise/core/networking/interceptors/Authenticator.kt
  src/main/java/be/appwise/core/networking/interceptors/HeaderInterceptor.kt
Labels: enhancement

#31 Better logoutstep in BaseNetworkingListeners
  src/main/java/be/appwise/core/networking/base/BaseNetworkingListeners.kt
Labels: enhancement

#41 Fading edge will now work even when there is padding on the RecyclerView
  src/main/java/be/appwise/core/ui/custom/RecyclerViewEmptyLoadingSupport.kt
Labels: bug

#3 NavController.tryNavigate
  src/main/java/be/appwise/core/extensions/navigation/NavControllerExtensions.kt
Labels: enhancement

#32 #13 Tested the issue and added a possible solution.
  src/main/java/be/appwise/core/networking/base/BaseNetworkingListeners.kt
Labels: bug, enhancement

#44 Kotlin version is needed in order to fix our build issues with Depend…
  build.gradle
Labels: breaking, bug

#45 BaseEntity requires an Any now instead of a fixed Int
  src/main/java/be/appwise/core/data/base/BaseEntity.kt
Labels: bug

#46 The function now expects a RecyclerView.ItemDecoration, added a KDoc,…
  src/main/java/be/appwise/core/extensions/view/RecyclerViewExtensions.kt
Labels: bug, documentation

#47 Added more documentation
  src/main/java/be/appwise/core/networking/base/BaseRestClient.kt
Labels: documentation

#52 Removing Realm from the project
  build.gradle
  src/main/java/be/appwise/core/networking/Networking.kt
  src/main/java/be/appwise/core/networking/base/BaseNetworkingListeners.kt
Labels: bug, dependencies

#58 Removing the default values from the parameters and added a bit more …
  src/main/java/be/appwise/core/core/CoreBuilder.kt
Labels: bug, documentation

#60 Went ahead and added the contributing and changelog files, also updat…
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  static/RestClient-flexibility.png
Labels: documentation
