Repository wisemen-digital/AndroidCore, pull requests merged in 2025-02, with the labels that each got.

#305 Convert gradle scripts to use kotlin dsl
  build.gradle
  build.gradle.kts
  core/build.gradle
  core/build.gradle.kts
  core/proguard-rules.pro
  data/networking/build.gradle
  data/networking/build.gradle.kts
  data/networking/proguard-rules.pro
  data/networking/proxyman/build.gradle
  data/networking/proxyman/build.gradle.kts
  data/networking/proxyman/proguard-rules.pro
  data/networking/proxyman/src/main/java/be/appwise/proxyman/ProxyManNetworkDiscoveryManager.kt
  data/networking/src/main/java/be/appwise/networking/bagel/BagelMessage.kt
  data/networking/src/main/java/be/appwise/networking/responseAdapter/DeferredNetworkResponseAdapter.kt
  data/paging/build.gradle
  data/paging/build.gradle.kts
  data/paging/proguard-rules.pro
  data/room/build.gradle
  data/room/build.gradle.kts
  data/room/proguard-rules.pro
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  list/emptyRecyclerView/build.gradle
  list/emptyRecyclerView/build.gradle.kts
  list/emptyRecyclerView/proguard-rules.pro
  sample/build.gradle
  sample/build.gradle.kts
  sample/proguard-rules.pro
  sample/src/main/java/com/example/coredemo/MyApp.kt
  sample/src/main/java/com/example/coredemo/ui/networking/ApiService.kt
  settings.gradle
  settings.gradle.kts
  views/dataRow/build.gradle
  views/dataRow/build.gradle.kts
  views/dataRow/proguard-rules.pro
Labels: 📃 XL PR

#398 Remove Bagel support
  data/networking/src/main/java/be/appwise/networking/NetworkConstants.kt
  data/networking/src/main/java/be/appwise/networking/bagel/BagelInterceptor.kt
  data/networking/src/main/java/be/appwise/networking/bagel/BagelMessage.kt
  data/networking/src/main/java/be/appwise/networking/bagel/BagelNetworkDiscoveryManager.kt
  data/networking/src/main/java/be/appwise/networking/base/BaseRestClient.kt
Labels: 📃 M PR, ✨ feature

#338 Feature/base classes v2
  build.gradle.kts
  core-compose/build.gradle.kts
  core-compose/src/main/java/be/appwise/compose/core/ui/base/BaseComposeStateViewModel.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/BaseComposeViewModel.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/snackbar/BaseSnackbar.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/snackbar/SnackbarTypes.kt
  core/build.gradle.kts
  core/src/main/java/be/appwise/core/ui/base/BaseActivity.kt
  core/src/main/java/be/appwise/core/ui/base/BaseApp.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingActivity.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingVMDialogFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseDialogFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseViewModel.kt
  core/src/main/java/be/appwise/core/util/SingleLiveEvent.kt
  data/networking/build.gradle.kts
  data/networking/proxyman/build.gradle.kts
  data/paging/build.gradle.kts
  data/room/build.gradle.kts
  gradle/libs.versions.toml
  list/emptyRecyclerView/build.gradle.kts
  sample/build.gradle.kts
  settings.gradle
  settings.gradle.kts
  views/dataRow/build.gradle.kts
Labels: 📃 L PR, ✨ feature

#399 Core v2
  build.gradle.kts
  core-compose/.gitignore
  core-compose/build.gradle.kts
  core-compose/consumer-rules.pro
  core-compose/proguard-rules.pro
  core-compose/src/main/AndroidManifest.xml
  core-compose/src/main/java/be/appwise/compose/core/ui/base/BaseComposeStateViewModel.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/BaseComposeViewModel.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/snackbar/BaseSnackbar.kt
  core-compose/src/main/java/be/appwise/compose/core/ui/base/snackbar/SnackbarTypes.kt
  core/build.gradle.kts
  core/src/main/java/be/appwise/core/ui/base/BaseActivity.kt
  core/src/main/java/be/appwise/core/ui/base/BaseApp.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingActivity.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseBindingVMDialogFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseDialogFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseFragment.kt
  core/src/main/java/be/appwise/core/ui/base/BaseViewModel.kt
  core/src/main/java/be/appwise/core/util/SingleLiveEvent.kt
  data/networking/build.gradle.kts
  data/networking/proxyman/build.gradle.kts
  data/paging/build.gradle.kts
  data/room/build.gradle.kts
  gradle/libs.versions.toml
  list/emptyRecyclerView/build.gradle.kts
  sample/build.gradle.kts
  settings.gradle.kts
  views/dataRow/build.gradle.kts
Labels: 📃 L PR

#400 removed realm documentation, added to changelog
  CHANGELOG.md
  README.md
  documentation/REALM.md
Labels: 📃 S PR

#402 Add Maven Publish Plugin and Configuration
  README.md
  core/build.gradle.kts
  data/networking/build.gradle.kts
  data/networking/proxyman/build.gradle.kts
  data/paging/build.gradle.kts
  data/room/build.gradle.kts
  documentation/CORE.md
  documentation/NETWORKING.md
  documentation/PAGING.md
  documentation/ROOM.md
  list/emptyRecyclerView/build.gradle.kts
  views/dataRow/build.gradle.kts
Labels: 📃 XS PR

#403 release 1.5.1
  CHANGELOG.md
Labels: 📃 XS PR

#404 release 1.5.1
  CHANGELOG.md
  README.md
  core/build.gradle.kts
  data/networking/build.gradle.kts
  data/networking/proxyman/build.gradle.kts
  data/paging/build.gradle.kts
  data/room/build.gradle.kts
  documentation/CORE.md
  documentation/NETWORKING.md
  documentation/PAGING.md
  documentation/ROOM.md
  list/emptyRecyclerView/build.gradle.kts
  views/dataRow/build.gradle.kts
Labels: 📃 XS PR

#409 release 1.5.2
  gradle/libs.versions.toml
Labels: 📃 XS PR
